CREATE TABLE [dbo].[Subcategory]
(
	[SubcategoryId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[CategoryId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(100) NOT NULL,
	[CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[ModifiedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
    CONSTRAINT [FK_Subcategory_ToCategory] FOREIGN KEY ([CategoryId]) REFERENCES [Category]([CategoryId])
)